import pandas as pd
import numpy as np
import plotly.graph_objects as go
from plotly.subplots import make_subplots
import sys
import os

# Add the scripts directory to path to import dft_utils if running from within scripts/
sys.path.append(os.path.dirname(__file__))
from dft_utils import load_cplx_data

def main():
    if len(sys.argv) < 2:
        print("Usage: python plot_dft.py <base_filename>")
        print("Example: python plot_dft.py testout")
        sys.exit(1)

    base_name = sys.argv[1]
    
    # Files generated by dft_frontend.c
    in_file = f"{base_name}_in"
    dft_file = f"{base_name}_dft"

    print(f"Loading data for {base_name}...")
    
    sig_in = load_cplx_data(in_file)
    sig_dft = load_cplx_data(dft_file)

    if sig_in is None:
        print(f"Error: Could not load input signal {in_file}")
        sys.exit(1)

    # Calculate Numpy FFT for comparison
    n_fft = len(sig_dft) if sig_dft is not None else len(sig_in)
    
    # Numpy defaults to no normalization for forward, so use 'ortho' to match our 1/sqrt(N)
    numpy_dft = np.fft.fft(sig_in, n=n_fft, norm='ortho')
    
    # Create subplots
    fig = make_subplots(rows=2, cols=1, 
                        subplot_titles=(f"Time Domain (Input Signal, len={len(sig_in)})", 
                                        f"Frequency Domain (FFT Magnitude, N={n_fft})"))

    # Plot Input Signal (Real part)
    fig.add_trace(go.Scatter(y=np.real(sig_in), name="Input (Real)", mode='lines'), row=1, col=1)

    # Plot FFT Magnitudes
    if sig_dft is not None:
        fig.add_trace(go.Scatter(y=np.abs(sig_dft), name="Frontend FFT", mode='lines', 
                                 line=dict(width=4, color='rgba(0, 0, 255, 0.5)')), row=2, col=1)
    
    fig.add_trace(go.Scatter(y=np.abs(numpy_dft), name="Numpy FFT", mode='lines',
                             line=dict(dash='dash', color='red')), row=2, col=1)

    fig.update_layout(height=800, title_text=f"DFT Analysis: {base_name}", showlegend=True)
    fig.update_xaxes(title_text="Sample Index", row=1, col=1)
    fig.update_xaxes(title_text="Frequency Bin", row=2, col=1)
    fig.update_yaxes(title_text="Amplitude", row=1, col=1)
    fig.update_yaxes(title_text="Magnitude", row=2, col=1)

    output_html = f"{base_name}_plot.html"
    fig.write_html(output_html)
    print(f"Plot saved to {output_html}")
    
    # Try to open it
    if sys.platform == 'win32':
        os.startfile(output_html)
    elif sys.platform == 'darwin':
        os.system(f"open {output_html}")
    else:
        os.system(f"xdg-open {output_html}")

if __name__ == "__main__":
    main()
